# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
louis = Author.create(name: "Louis van Gaal")
Quote.create(author: louis, content: "Ik weet dat ik een hele goede coach ben!")
Quote.create(author: louis, content: "0-0 is een grote uitslag.")
Quote.create(author: louis, content: "Als ik God zou zijn, zou ik alles winnen. Maar ik ben God niet.")
Quote.create(author: louis, content: "Als ik een fout maak kan ik er slapeloze nachten van hebben. Maar dat overkomt me zelden.")
Quote.create(author: louis, content: "U moet ‘waarom-vragen’ stellen en geen stellingen poneren. Als je stellingen poneert, wil dat zeggen dat je net zoveel verstand hebt als de trainer. En volgens mij is trainen een vak, net als journalist zijn. Dus schoenmaker, blijf bij je leest. Geen enkele journalist heeft er net zoveel verstand van als ik. Echt niet. ")
Quote.create(author: louis, content: "Er wordt gezegd dat er binnen Ajax nu volgens de Cruijff-lijn wordt gewerkt. Onzin! Er is net zo min een Cruijff-lijn als een Van Gaal-lijn. Er bestaat alleen maar een Ajax-visie en die is er al zeker 25 jaar. Ik heb daar ook aan bijgedragen net als Cruijff, alleen heb ik er langer gewerkt. ")
Quote.create(author: louis, content: "Ik wachtte op een land. En toen werd het Oranje. Mooier kan niet. Eigenlijk heb ik hier op gewacht.")
Quote.create(author: louis, content: "Ik weet dat de buitenwereld mij als een autoritaire man beschouwt. Daar lig ik niet wakker van, maar het klopt niet. Mensen die dicht bij mij staan, weten dat ik anti-autoritair ben. Ik kies voor een democratisch leiderschap. Maar uiteindelijk zal er toch iemand moeten beslissen, en dat ben ik dan.")
Quote.create(author: louis, content: "Als je grenzen aangeeft, kunnen mensen zich daarbinnen vrij bewegen.")
Quote.create(author: louis, content: "Qua geld en organisatie is Bayern fantastisch. Ik heb nooit bij professionelere club gewerkt dan Bayern. Ik heb ook nergens zo veel verdiend als bij Bayern.")
Quote.create(author: louis, content: "In het topvoetbal zijn de omschakelmomenten cruciaal omdat er dan vaak sprake is van een gebrek aan organisatie bij het team dat de bal verliest.")
Quote.create(author: louis, content: "Amigos de la prensa, yo me voy. Felicidades.", subtitle: "Vrienden van de pers, ik ga weg. Gefeliciteerd., Persconferentie naar aanleiding van zijn vertrek bij FC Barcelona, 20 mei 2000")
Quote.create(author: louis, content: "Ben ik nu degene die zo slim is, of ben jij nou zo dom? ")
Quote.create(author: louis, content: "Dat mag jij vinden, want daarvoor ben je een volwassen man.")
Quote.create(author: louis, content: "Ik heb in dat geweldige gesprek gezegd: de eerste keer dat jij een bal afpakt ga jij een trainer zien, die gaat JUICHEN.", subtitle: "Van Gaal onthult wat hij Wesley Sneijder vertelde in een één-op-één gesprek met de middenvelder.")
Quote.create(author: louis, content: "De mentaliteit bij Bayern past perfect bij me. Waarom? Het motto is hier ‘we zijn wie we zijn’. En ik ben wie ik ben: zelfverzekerd, arrogant, dominant, eerlijk, hard werkend en vernieuwend.")
Quote.create(author: louis, content: "Ik houd van hun mentaliteit, ze zijn ongelooflijk. Ze zijn nog fanatieker dan ik.", subtitle: "Over Duitse voetballers.")
Quote.create(author: louis, content: "Ik heb in zes jaar bij Ajax meer bereikt dan Barcelona in honderd jaar.")
Quote.create(author: louis, content: "De weg naar succes is altijd onder constructie.")
Quote.create(author: louis, content: "Rennen is voor beesten. Je hebt een brein en een bal nodig voor voetbal.")
Quote.create(author: louis, content: "Er zijn geen stomme vragen. Er zijn stomme mensen.")
Quote.create(author: louis, content: "Erkenning is voor mij belangrijker dan geld. Zeker de erkenning van mijn spelers.")
Quote.create(author: louis, content: "Je kunt van mijn gezicht aflezen wat ik voel, wat ik zeg, wat ik denk en de volgende dag weet ik nog steeds wat ik gezegd heb.")
Quote.create(author: louis, content: "Rennen is voor beesten. Je hebt een brein en een bal nodig voor voetbal.")
Quote.create(author: louis, content: "Guardiola hangt de filosofie van Louis van Gaal aan. Ik denk dat het een fantastische keuze is.")
Quote.create(author: louis, content: "Es ist wieder ein Spiel – der Tod oder die Gladiolen.")
Quote.create(author: louis, content: "De Nederlandse top! De competitie in Engeland is niet beter dan die in Nederland. In Nederland kunnen misschien maar vier Engelse clubs de landstitel veroveren. Het niveau van de clubs in de Nederlandse competitie is hoog.")
Quote.create(author: louis, content: "Gefeliciteerd met de beste trainer ter wereld.", subtitle: "Bij zijn aanstelling bij Ajax")
Quote.create(author: louis, content: "Ich Schlafe immer löffel an löffel")
Quote.create(author: louis, content: "Ik beslis zelf met welke formatie ik speel. Geen directeur zegt hoe ik speel. Ja, Uli Hoeness deed dat even bij Bayern München. Daarom ben ik weggegaan.")
Quote.create(author: louis, content: "Iedereen mag zijn mening geven, maar het is die van jou die zo stom is!")
Quote.create(author: louis, content: "Met zo’n trainer kan Argentinië geen wereldkampioen worden. Trainer zijn is een beroep, waarvoor je opgeleid dient te worden. Het is geen hobby, je bent niet zomaar trainer.", subtitle: "Na de aanstelling van Diego Maradona als bondscoach.")
Quote.create(author: louis, content: "Ik heb in zes jaar bij Ajax meer bereikt dan Barcelona in honderd jaar")
Quote.create(author: louis, content: "The three points are inside!", subtitle: "Na zijn eerste overwinning")
Quote.create(author: louis, content: "I am a crazy coach, but for the so much time I had to change my team.", subtitle: "Meneer is niet blij met het aantal blessures in zijn selectie.")
Quote.create(author: louis, content: "Ja, it is again the same song.", subtitle: "Over een gelijkspel tegen Chelsea.")
Quote.create(author: louis, content: "Het is not so difficult hoor!")
Quote.create(author: louis, content: "We always did the light out, with a glass of wine.", subtitle: "Over een goed gesprek met zijn ‘vriend’ Sir Alex Ferguson.")
Quote.create(author: louis, content: "If you play good, and listen good, you can play good.")
Quote.create(author: louis, content: "This question is over the line.", subtitle: "Een journalist vraagt naar de blessure van Robin van Persie.")
Quote.create(author: louis, content: "Chelsea is another cook. Chelsea is another biscuit.")
Quote.create(author: louis, content: "That is not very smart, that I can say.", subtitle: "Over een domme gele kaart van Chris Smalling.")
Quote.create(author: louis, content: "I feel myself very lousy for the fans.", subtitle: "Na wat slechte resultaten met het elftal")
Quote.create(author: louis, content: "We are running behind the facts.")
Quote.create(author: louis, content: "It’s a question of time.")
Quote.create(author: louis, content: "When I think I’ve made an error, it can cause me a sleepless night. But that only happens rarely.")

johan = Author.create(name: "Johan Cruijff")

Quote.create(author: johan, content: "Winnen doe je met z’n allen.")
Quote.create(author: johan, content: "Elk nadeel heeft zijn voordeel.")
Quote.create(author: johan, content: "Je moet schieten, anders kun je niet scoren.")
Quote.create(author: johan, content: "Ik ben het Nederlands belangrijkste exportproduct.")
Quote.create(author: johan, content: "Ik weet meer dan niets van volleybal en dat is genoeg.")
Quote.create(author: johan, content: "Ik maak eigenlijk zelden fouten, want ik heb moeite me te vergissen.")
Quote.create(author: johan, content: "Ik ben overal tegen. Tot ik een besluit neem, dan ben ik ervoor.")
Quote.create(author: johan, content: "De waarheid is nooit precies zoals je denkt dat hij zou zijn.")
Quote.create(author: johan, content: "Ik geloof niet. In spanje slaan alle 22 spelers een kruisje voordat ze het veld opkomen, als het werkt, zal het dus altijd een gelijkspel worden.")
Quote.create(author: johan, content: "Voor een slechte voetballer heeft hij een hele goede techniek. Maar voor een goede voetballer heeft hij juist een slechte techniek.", subtitle: "over Zlatan Ibrahimovic")
Quote.create(author: johan, content: "Wat is snelheid? Vaak verwisselt de sportpers snelheid met inzicht. Kijk, als ik iets eerder begin te lopen dan een ander, dan lijk ik sneller.")
Quote.create(author: johan, content: "Voetbal hoort gespeeld te worden in een 4-3-3 opstelling. Je kunt niet met twee spitsen spelen, want dan krijg je oneven getallen en kan een elftal nooit functioneren.")
Quote.create(author: johan, content: "Er zijn in een wedstrijd drie minuten – en die natuurlijk onderverdeeld in momenten – waar het op aankomt.")
Quote.create(author: johan, content: "Voordat ik een fout maak, maak ik die fout niet.")
Quote.create(author: johan, content: "In zekere zin ben ik waarschijnlijk onsterfelijk.")
Quote.create(author: johan, content: "Het leven is een stroom zeggen de mensen. Dat klopt. Toen ik laatst tegen de wind in wou spuwen, spoog ik mezelf in het gezicht.")
Quote.create(author: johan, content: "De zege van al die gelijkmakers is hun stellige ondergang.")
Quote.create(author: johan, content: "Hun verdediging was geitenkaas.")
Quote.create(author: johan, content: "De hoogste opgave van het menselijk kennen is: te begrijpen dat hij niet begrijpen kan.")
Quote.create(author: johan, content: "Er is nu eenheid, iedereen doet in principe wat ik vraag. Het zijn namelijk geen Hollanders, die als je begint met ademhalen al zeggen: ja maar…")
Quote.create(author: johan, content: "Als ik een bal aan de voet heb die ik wil afspelen, dan moet ik rekening houden met mijn bewaker, de wind, het gras, de snelheid waarmee de spelers lopen. Wij berekenen de kracht waarmee je moet schoppen en de richting waarin in ééntiende seconde. Een computer doet daar twee minuten over!")
Quote.create(author: johan, content: "Je gaat het pas zien als je het doorhebt.")
Quote.create(author: johan, content: "Als ik thuiskom van een televisie-analyse, vraagt mijn vrouw: Wat heb je gezegd? Dan zeg ik: Al sla je me dood.")
Quote.create(author: johan, content: "Als mijn spelers zichzelf en de club belachelijk willen maken, moeten ze dat maar negentig minuten lang doen.", subtitle: "waarom hij geen wissels doorvoerde.")
Quote.create(author: johan, content: "Het gat dat overblijft in de kruising…")
Quote.create(author: johan, content: "Met geld maak je geld.")
Quote.create(author: johan, content: "De één zet muziek op de andere dansen mee.")
Quote.create(author: johan, content: "Ik heb een vreselijke hekel aan iemand die beweegt, maar niet weet waar naartoe.")
Quote.create(author: johan, content: "Als met 4-0 voorstaat is het beter om de bal met een lob op de lat te schieten dan te scoren.")
Quote.create(author: johan, content: "Simpel spelen is het mooist.")
Quote.create(author: johan, content: "Er moet op elke plaats in het veld verdedigd worden dat kost het minste energie want dan moet je niet helemaal terug lopen om een doelpunt te maken.")
Quote.create(author: johan, content: "Je kan ook goed spelen zonder een bal te raken.")
Quote.create(author: johan, content: "Je wordt beter door slechter te worden.")
Quote.create(author: johan, content: "Cruijff heeft nooit gemerkt dat je van rondjes rennen beter wordt, in het moderne voetbal gaat het om korte snelle sprintjes.")
Quote.create(author: johan, content: "Ik geniet van een 4-3 overwinning. Ik schaam me voor een door middel van een counter behaalde 1-0 overwinning.")
Quote.create(author: johan, content: "De keeper voetbalt mee als laatste verdediger. Hij schiet de bal nooit hoog en hard naar voren maar rolt hem uit, want je kan alleen maar doelpunten maken als je de bal hebt.")
Quote.create(author: johan, content: "De bal ineens spelen vraagt meer techniek dan hem 2000 keer hooghouden.")
Quote.create(author: johan, content: "Voor vrijlopen heb je techniek nodig.")
Quote.create(author: johan, content: "Als iedereen zijn taak doet speel je op zijn minst gelijk.")
Quote.create(author: johan, content: "Hoe simpeler hoe beter want hoe minder keuze je een speler laat hoe meer kans dat hij het juiste doet.")
Quote.create(author: johan, content: "Vindt de zwakke plek van je tegenstander en je hebt gewonnen.")
Quote.create(author: johan, content: "We zijn op zoek gegaan naar de overwinning en dan kom je hem vanzelf tegen.")
Quote.create(author: johan, content: "Als je verstand van voetbal had zou jij hier zitten.")
Quote.create(author: johan, content: "Winnen is logish, verliezen niet.")
Quote.create(author: johan, content: "Voetbal speel je met het hoofd, want de bal is vlugger dan de benen.")
Quote.create(author: johan, content: "Het leukste van trainer zijn is spelletjes verzinnen waarin je zelf kunt meedoen.")
Quote.create(author: johan, content: "Bandage is zeer aantrekkelijk voor de tegenstander.")
Quote.create(author: johan, content: "Je hebt voetbalsituaties en situaties die voortkomen uit vechten, ik zie liever een voetbalsituatie.")
Quote.create(author: johan, content: "De basis van het spel is om de bal zo snel mogelijk onder controle te krijgen, zodat je meer tijd hebt om te kijken.")
Quote.create(author: johan, content: "De punten moeten dáár op de i gezet worden, waar ze horen.")
Quote.create(author: johan, content: "Hoe simpeler hoe beter. Want hoe minder keuze je een speler laat, hoe groter de kans dat hij het juiste doet.")
Quote.create(author: johan, content: "Soms moet er iets gebeuren voordat er iets gebeurt.")
Quote.create(author: johan, content: "Ik hou van werken zolang het werken is waarvan ik hou.")
Quote.create(author: johan, content: "Voordat ik een fout maak, maak ik die fout niet.")
Quote.create(author: johan, content: "Je kan beter ten onder gaan met je eigen visie als met de visie van een ander.")
Quote.create(author: johan, content: "Voetbal is simpel: je bent op tijd of je bent te laat. Als je te laat bent moet je eerder vertrekken.")
Quote.create(author: johan, content: "Om te beginnen is er maar één bal en die moet je dus hebben, maar waar het dus in wezen om gaat, is: wat doe je met die bal?")
Quote.create(author: johan, content: "Voetbal is een spel van fouten. Wie de minste fouten maakt wint.")
Quote.create(author: johan, content: "Voor een slechte voetballer heeft hij een hele goede techniek. Maar voor een goede voetballer heeft hij juist een slechte techniek.")
Quote.create(author: johan, content: "Voetbal is simpel. Het is echter moeilijk om simpel te voetballen.")
Quote.create(author: johan, content: "Wat is snelheid? Vaak verwisselt de sportpers snelheid met inzicht. Kijk, als ik iets eerder begin te lopen dan een ander, dan lijk ik sneller.")
Quote.create(author: johan, content: "Als wij de bal hebben, kunnen zij niet scoren.")
Quote.create(author: johan, content: "Als ik zou willen dat je het begreep, had ik het wel beter uitgelegd.")
Quote.create(author: johan, content: "Als je op balbezit speelt, hoef je niet te verdedigen want er is maar één bal.")
Quote.create(author: johan, content: "Je wordt beter door slechter te worden.")
Quote.create(author: johan, content: "Ik ben er nog steeds van overtuigd dat zoals ik het doe je het moet doen want anders zou ik het niet doen.")
Quote.create(author: johan, content: "We zijn op zoek gegaan naar de overwinning en dan kom je hem vanzelf tegen.")
Quote.create(author: johan, content: "Als je sneller wilt spelen kun je wel harder lopen maar in weze bepaalt de bal de snelheid van het spel.")
Quote.create(author: johan, content: "Je moet altijd zorgen dat je een doelpunt meer scoort als de tegenstander.")
Quote.create(author: johan, content: "Je moet de bal hebben om te schieten, en schieten om te scoren, maar dat is logisch.")
Quote.create(author: johan, content: "Kijk, de bal moet minimaal tussen die twee palen, maar dat is logisch.")
Quote.create(author: johan, content: "Het Nederlands elftal moet sowieso winnen, dus blijft verliezen of gelijk spel over.")
Quote.create(author: johan, content: "Als je niet kan winnen, moet je zorgen dat je niet verliest.")
Quote.create(author: johan, content: "Wij hebben het uitstekend gedaan, simpelweg omdat we niet beter konden.")