# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
louis = Author.create(name: "Louis van Gaal")
Quote.create(author: louis, content: "Ik weet dat ik een hele goede coach ben!")
Quote.create(author: louis, content: "0-0 is een grote uitslag.")
Quote.create(author: louis, content: "Als ik God zou zijn, zou ik alles winnen. Maar ik ben God niet.")
Quote.create(author: louis, content: "Als ik een fout maak kan ik er slapeloze nachten van hebben. Maar dat overkomt me zelden.")
Quote.create(author: louis, content: "U moet ‘waarom-vragen’ stellen en geen stellingen poneren. Als je stellingen poneert, wil dat zeggen dat je net zoveel verstand hebt als de trainer. En volgens mij is trainen een vak, net als journalist zijn. Dus schoenmaker, blijf bij je leest. Geen enkele journalist heeft er net zoveel verstand van als ik. Echt niet. ")
Quote.create(author: louis, content: "Er wordt gezegd dat er binnen Ajax nu volgens de Cruijff-lijn wordt gewerkt. Onzin! Er is net zo min een Cruijff-lijn als een Van Gaal-lijn. Er bestaat alleen maar een Ajax-visie en die is er al zeker 25 jaar. Ik heb daar ook aan bijgedragen net als Cruijff, alleen heb ik er langer gewerkt. ")
Quote.create(author: louis, content: "Ik wachtte op een land. En toen werd het Oranje. Mooier kan niet. Eigenlijk heb ik hier op gewacht.")
Quote.create(author: louis, content: "Ik weet dat de buitenwereld mij als een autoritaire man beschouwt. Daar lig ik niet wakker van, maar het klopt niet. Mensen die dicht bij mij staan, weten dat ik anti-autoritair ben. Ik kies voor een democratisch leiderschap. Maar uiteindelijk zal er toch iemand moeten beslissen, en dat ben ik dan.")
Quote.create(author: louis, content: "Als je grenzen aangeeft, kunnen mensen zich daarbinnen vrij bewegen.")
Quote.create(author: louis, content: "Qua geld en organisatie is Bayern fantastisch. Ik heb nooit bij professionelere club gewerkt dan Bayern. Ik heb ook nergens zo veel verdiend als bij Bayern.")
Quote.create(author: louis, content: "In het topvoetbal zijn de omschakelmomenten cruciaal omdat er dan vaak sprake is van een gebrek aan organisatie bij het team dat de bal verliest.")
Quote.create(author: louis, content: "Amigos de la prensa, yo me voy. Felicidades.", subtitle: "Vrienden van de pers, ik ga weg. Gefeliciteerd., Persconferentie naar aanleiding van zijn vertrek bij FC Barcelona, 20 mei 2000")
Quote.create(author: louis, content: "Ben ik nu degene die zo slim is, of ben jij nou zo dom? ")
Quote.create(author: louis, content: "Dat mag jij vinden, want daarvoor ben je een volwassen man.")
Quote.create(author: louis, content: "Ik heb in dat geweldige gesprek gezegd: de eerste keer dat jij een bal afpakt ga jij een trainer zien, die gaat JUICHEN.", subtitle: "Van Gaal onthult wat hij Wesley Sneijder vertelde in een één-op-één gesprek met de middenvelder.")
Quote.create(author: louis, content: "De mentaliteit bij Bayern past perfect bij me. Waarom? Het motto is hier ‘we zijn wie we zijn’. En ik ben wie ik ben: zelfverzekerd, arrogant, dominant, eerlijk, hard werkend en vernieuwend.")
Quote.create(author: louis, content: "Ik houd van hun mentaliteit, ze zijn ongelooflijk. Ze zijn nog fanatieker dan ik.", subtitle: "Over Duitse voetballers.")
Quote.create(author: louis, content: "Ik heb in zes jaar bij Ajax meer bereikt dan Barcelona in honderd jaar.")
Quote.create(author: louis, content: "De weg naar succes is altijd onder constructie.")
Quote.create(author: louis, content: "Rennen is voor beesten. Je hebt een brein en een bal nodig voor voetbal.")
Quote.create(author: louis, content: "Er zijn geen stomme vragen. Er zijn stomme mensen.")
Quote.create(author: louis, content: "Erkenning is voor mij belangrijker dan geld. Zeker de erkenning van mijn spelers.")
Quote.create(author: louis, content: "Je kunt van mijn gezicht aflezen wat ik voel, wat ik zeg, wat ik denk en de volgende dag weet ik nog steeds wat ik gezegd heb.")
Quote.create(author: louis, content: "Rennen is voor beesten. Je hebt een brein en een bal nodig voor voetbal.")
Quote.create(author: louis, content: "Guardiola hangt de filosofie van Louis van Gaal aan. Ik denk dat het een fantastische keuze is.")
Quote.create(author: louis, content: "Es ist wieder ein Spiel – der Tod oder die Gladiolen.")
Quote.create(author: louis, content: "De Nederlandse top! De competitie in Engeland is niet beter dan die in Nederland. In Nederland kunnen misschien maar vier Engelse clubs de landstitel veroveren. Het niveau van de clubs in de Nederlandse competitie is hoog.")
Quote.create(author: louis, content: "Gefeliciteerd met de beste trainer ter wereld.", subtitle: "Bij zijn aanstelling bij Ajax")
Quote.create(author: louis, content: "Ich Schlafe immer löffel an löffel")
Quote.create(author: louis, content: "Ik beslis zelf met welke formatie ik speel. Geen directeur zegt hoe ik speel. Ja, Uli Hoeness deed dat even bij Bayern München. Daarom ben ik weggegaan.")
Quote.create(author: louis, content: "Iedereen mag zijn mening geven, maar het is die van jou die zo stom is!")
Quote.create(author: louis, content: "Met zo’n trainer kan Argentinië geen wereldkampioen worden. Trainer zijn is een beroep, waarvoor je opgeleid dient te worden. Het is geen hobby, je bent niet zomaar trainer.", subtitle: "Na de aanstelling van Diego Maradona als bondscoach.")
Quote.create(author: louis, content: "Ik heb in zes jaar bij Ajax meer bereikt dan Barcelona in honderd jaar")